### PR TITLE
add PR file encoding checker workflow template

### PR DESCRIPTION
**Pull request by cjyetman**
based on https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template

### CODE REVIEW

**Comment by cjyetman** [comment]
this PR is not yet complete

according to [this](https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template), apparently for this to work, an SVG icon is *required*, and must be specified by filename without the extension [here](https://github.com/2DegreesInvesting/.github/blob/681c7d49200821cb49a16e522c69c195c016fed9/.github/workflow-templates/pr-file-encodings.properties.json#L4)

**Comment by cjyetman** [comment]
looks like GitHub is functioning properly again, and the SVG icon and its setting are in the commits here.... so I believe this PR is ready to go

to be honest, I don't know if/how this can be tested until it has already been merged

**Review by maurolepore — APPROVED** [review]
LGTM. Thanks! Maybe you can demo this during the next sprint planning or dev-hangout?

**Comment by cjyetman** [comment]
hmmmm... unfortunately, it doesn't seem to be working as is suggested [here](https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#using-a-workflow-template-from-your-organization)

**Pull request merged**
